# Generated by Django 2.0.2 on 2018-02-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_result_suite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='content',
            new_name='log_content',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='suite',
            new_name='origin_suite',
        ),
        migrations.AddField(
            model_name='result',
            name='suite_content',
            field=models.TextField(null=True),
        ),
    ]
